### PR TITLE
release version 3.0.0

### PR DESCRIPTION
**Pull request by rrennick**
Fixes from RC 4

- Mark action as migrated if source delete fails
- Add post store `$args` length dependency check
- Improve error message when `$args` exceeds length limit

### CODE REVIEW

**Comment by unfulvio** [comment]
hey there and happy new year, when is this due to be released? along with WC 3.9?

**Comment by rrennick** [comment]
> along with WC 3.9?

No, it's not being coordinated with the WC release. We hope to release it early next week.

**Comment by james-allan** [comment]
@unfulvio It'll be released in Subscriptions 3.0 which is planned for next week.

**Comment by unfulvio** [comment]
awesome news, thanks @james-allan - happy new year too

**Comment by james-allan** [comment]
A happy new year to you and the team there too @unfulvio :) 

LGTM. Thanks @rrennick.

**Pull request merged**
